### PR TITLE
Update build.yml

### PR DESCRIPTION
**Pull request by vineetbansal**
Let cibuildwheel build for py 3.10 too

### CODE REVIEW

**Comment by vineetbansal** [comment]
@bstellato - I think this can be merged, and perhaps we release new wheels for qdldl to address:
https://github.com/osqp/osqp-python/issues/68

**Review by bstellato — APPROVED** [review]

**Comment by bstellato** [comment]
LGTM. Thank you, @vineetbansal !

**Comment by h-vetinari** [comment]
The compiler version shouldn't be hard-coded into `setup.py`, but dealt with from the CI side. As-is, this makes the package uninstallable on windows with any other version than the very recent VS2022, which is unnecessarily restrictive - and we're hitting this in https://github.com/conda-forge/qdldl-python-feedstock/pull/14, for example.

**Comment by vineetbansal** [comment]
@h-vetinari - Fair enough. The following changes are due to be merged to `master`:
https://github.com/osqp/qdldl-python/pull/22/files

We're passing in `CMAKE_GENERATOR` and `CMAKE_GENERATOR_PLATFORM` as environment variables, and not hardcoding them in `setup.py`. To replicate old behavior, the former can be specified as `Visual Studio 14 2015 Win64` and the latter left unspecified.

Can you let us know if these changes will not work for your workflow? If not, we'll have these merged this week.

**Comment by h-vetinari** [comment]
Hey @vineetbansal, thank you for your response!

We'll be able to work around things even if things stay unchanged (just need to patch the source), but carrying patches makes life more difficult and thankfully your change in #22 makes such steps obsolete. Thank you! :)

**Pull request merged**
