### PR TITLE
Adds Solver.factors method

### PR DESCRIPTION
**Pull request by PTNobel**
Adds a function that returns `L, D, P` to `Solver`.

I still need to add tests, but I wanted to open this and see what people think.

Here was my development test case: 

```
import numpy as np
import scipy.sparse as sp
import qdldl

A = np.random.rand(10, 10)
A = A.T @ A

Acsc = sp.csc_matrix(A)
q = qdldl.Solver(Acsc)
L, D, P = q.factors()
L = L + sp.eye(10)
print(np.linalg.norm(L @ np.diag(D) @ L.T - A))
```

### CODE REVIEW

**Comment by bstellato** [comment]
That's great, @PTNobel! Sorry for the slow reply. 

Would you mind adding one/two quick python tests to make sure this does not break in the future?

**Comment by PTNobel** [comment]
Any preference on how to design the tests? Should I just hard code some matrixes and their factorizations? Or should I test that for the factors reconstruct A?

**Comment by bstellato** [comment]
I would add a simple test for a hard-coded `A`. We can check:
1. that the factors reconstruct the matrix `A`
2. That they have the desired properties, i.e., `L` lower-triangular and `D` diagonal

**Comment by PTNobel** [comment]
Does anyone know of a small matrix where the permutation in the factor is non-trivial?

Also, what is the factorization `P L D L^T P^T`? If so we should document that... (which I'll put in the factors docs).

**Comment by bstellato** [comment]
> Does anyone know of a small matrix where the permutation in the factor is non-trivial?

The sparser it is, the easier it is to get non-trivial permutatiojns

> Also, what is the factorization? Is it P L D L^T P^T? If so we should document that... (which I'll put in the factors docs).

Yes, it should be that one. See [here](https://github.com/osqp/qdldl-python/blob/de5390936b7d05cdc562bb1742985c6e92850026/cpp/qdldl.cpp#L85) for what happens under the hood

> Also, how do I add a doc comment (or otherwise add docs for .factors) with pybind11?

Docstrings should be easy to add in pybind11. Check [this](https://pybind11.readthedocs.io/en/stable/advanced/misc.html#generating-documentation-using-sphinx) out from their docs

**Comment by PTNobel** [comment]
Thank you @bstellato! The PR is ready to go on my end.

**Pull request merged**
